-- ─── Migration 040: Reseed role_permissions (idempotent) ─────────────────────
-- Chạy trong Supabase SQL Editor
-- Safe to re-run: dùng ON CONFLICT DO UPDATE
-- Sync với PERM_GROUPS trong app/dashboard/admin/page.tsx

INSERT INTO role_permissions (role_id, permission_key, is_enabled)
SELECT r.id, p.pkey, p.enabled
FROM (VALUES
  -- ── admin: toàn quyền ──────────────────────────────────────────────────────
  ('admin','VIEW_ALL_CUSTOMERS',     TRUE),
  ('admin','VIEW_OWN_CUSTOMERS',     TRUE),
  ('admin','CREATE_CUSTOMER',        TRUE),
  ('admin','MANAGE_CUSTOMER',        TRUE),
  ('admin','CREATE_QUOTE',           TRUE),
  ('admin','APPROVE_QUOTE',          TRUE),
  ('admin','CREATE_CONTRACT',        TRUE),
  ('admin','APPROVE_CONTRACT',       TRUE),
  ('admin','APPROVE_DISCOUNT',       TRUE),
  ('admin','START_TASK',             TRUE),
  ('admin','COMPLETE_OWN_TASK',      TRUE),
  ('admin','APPROVE_OTHERS_TASK',    TRUE),
  ('admin','MANAGE_BLOCKED_TASK',    TRUE),
  ('admin','VIEW_FINANCIAL_DATA',    TRUE),
  ('admin','COLLECT_PAYMENT',        TRUE),
  ('admin','VIEW_ALL_KPI',           TRUE),
  ('admin','MANAGE_USERS',           TRUE),
  ('admin','EDIT_SYSTEM_SETTINGS',   TRUE),
  ('admin','EDIT_TASK_DEFINITIONS',  TRUE),

  -- ── ceo: gần như admin, không edit system/task definitions ────────────────
  ('ceo','VIEW_ALL_CUSTOMERS',       TRUE),
  ('ceo','VIEW_OWN_CUSTOMERS',       TRUE),
  ('ceo','CREATE_CUSTOMER',          TRUE),
  ('ceo','MANAGE_CUSTOMER',          TRUE),
  ('ceo','CREATE_QUOTE',             TRUE),
  ('ceo','APPROVE_QUOTE',            TRUE),
  ('ceo','CREATE_CONTRACT',          TRUE),
  ('ceo','APPROVE_CONTRACT',         TRUE),
  ('ceo','APPROVE_DISCOUNT',         TRUE),
  ('ceo','START_TASK',               TRUE),
  ('ceo','COMPLETE_OWN_TASK',        TRUE),
  ('ceo','APPROVE_OTHERS_TASK',      TRUE),
  ('ceo','MANAGE_BLOCKED_TASK',      TRUE),
  ('ceo','VIEW_FINANCIAL_DATA',      TRUE),
  ('ceo','COLLECT_PAYMENT',          TRUE),
  ('ceo','VIEW_ALL_KPI',             TRUE),
  ('ceo','MANAGE_USERS',             TRUE),
  ('ceo','EDIT_SYSTEM_SETTINGS',     FALSE),
  ('ceo','EDIT_TASK_DEFINITIONS',    FALSE),

  -- ── director: phó GĐ + kỹ thuật, không manage users / system ─────────────
  ('director','VIEW_ALL_CUSTOMERS',  TRUE),
  ('director','VIEW_OWN_CUSTOMERS',  TRUE),
  ('director','CREATE_CUSTOMER',     TRUE),
  ('director','MANAGE_CUSTOMER',     TRUE),
  ('director','CREATE_QUOTE',        TRUE),
  ('director','APPROVE_QUOTE',       TRUE),
  ('director','CREATE_CONTRACT',     TRUE),
  ('director','APPROVE_CONTRACT',    TRUE),
  ('director','APPROVE_DISCOUNT',    TRUE),
  ('director','START_TASK',          TRUE),
  ('director','COMPLETE_OWN_TASK',   TRUE),
  ('director','APPROVE_OTHERS_TASK', TRUE),
  ('director','MANAGE_BLOCKED_TASK', TRUE),
  ('director','VIEW_FINANCIAL_DATA', TRUE),
  ('director','COLLECT_PAYMENT',     FALSE),
  ('director','VIEW_ALL_KPI',        TRUE),
  ('director','MANAGE_USERS',        FALSE),
  ('director','EDIT_SYSTEM_SETTINGS',FALSE),
  ('director','EDIT_TASK_DEFINITIONS',FALSE),

  -- ── accountant: tài chính + xem tất cả, không tạo/duyệt BG/HĐ ───────────
  ('accountant','VIEW_ALL_CUSTOMERS',TRUE),
  ('accountant','VIEW_OWN_CUSTOMERS',TRUE),
  ('accountant','CREATE_CUSTOMER',   FALSE),
  ('accountant','MANAGE_CUSTOMER',   FALSE),
  ('accountant','CREATE_QUOTE',      FALSE),
  ('accountant','APPROVE_QUOTE',     FALSE),
  ('accountant','CREATE_CONTRACT',   FALSE),
  ('accountant','APPROVE_CONTRACT',  FALSE),
  ('accountant','APPROVE_DISCOUNT',  FALSE),
  ('accountant','START_TASK',        TRUE),
  ('accountant','COMPLETE_OWN_TASK', TRUE),
  ('accountant','APPROVE_OTHERS_TASK',FALSE),
  ('accountant','MANAGE_BLOCKED_TASK',FALSE),
  ('accountant','VIEW_FINANCIAL_DATA',TRUE),
  ('accountant','COLLECT_PAYMENT',   TRUE),
  ('accountant','VIEW_ALL_KPI',      TRUE),
  ('accountant','MANAGE_USERS',      FALSE),
  ('accountant','EDIT_SYSTEM_SETTINGS',FALSE),
  ('accountant','EDIT_TASK_DEFINITIONS',FALSE),

  -- ── sales: chỉ KH của mình, tạo BG/HĐ, không duyệt, không xem tài chính
  ('sales','VIEW_ALL_CUSTOMERS',     FALSE),
  ('sales','VIEW_OWN_CUSTOMERS',     TRUE),
  ('sales','CREATE_CUSTOMER',        TRUE),
  ('sales','MANAGE_CUSTOMER',        TRUE),
  ('sales','CREATE_QUOTE',           TRUE),
  ('sales','APPROVE_QUOTE',          FALSE),
  ('sales','CREATE_CONTRACT',        TRUE),
  ('sales','APPROVE_CONTRACT',       FALSE),
  ('sales','APPROVE_DISCOUNT',       FALSE),
  ('sales','START_TASK',             TRUE),
  ('sales','COMPLETE_OWN_TASK',      TRUE),
  ('sales','APPROVE_OTHERS_TASK',    FALSE),
  ('sales','MANAGE_BLOCKED_TASK',    FALSE),
  ('sales','VIEW_FINANCIAL_DATA',    FALSE),
  ('sales','COLLECT_PAYMENT',        TRUE),
  ('sales','VIEW_ALL_KPI',           FALSE),
  ('sales','MANAGE_USERS',           FALSE),
  ('sales','EDIT_SYSTEM_SETTINGS',   FALSE),
  ('sales','EDIT_TASK_DEFINITIONS',  FALSE),

  -- ── tech: xem KH theo khu vực, tasks kỹ thuật ────────────────────────────
  ('tech','VIEW_ALL_CUSTOMERS',      FALSE),
  ('tech','VIEW_OWN_CUSTOMERS',      TRUE),
  ('tech','CREATE_CUSTOMER',         FALSE),
  ('tech','MANAGE_CUSTOMER',         FALSE),
  ('tech','CREATE_QUOTE',            FALSE),
  ('tech','APPROVE_QUOTE',           FALSE),
  ('tech','CREATE_CONTRACT',         FALSE),
  ('tech','APPROVE_CONTRACT',        FALSE),
  ('tech','APPROVE_DISCOUNT',        FALSE),
  ('tech','START_TASK',              TRUE),
  ('tech','COMPLETE_OWN_TASK',       TRUE),
  ('tech','APPROVE_OTHERS_TASK',     FALSE),
  ('tech','MANAGE_BLOCKED_TASK',     FALSE),
  ('tech','VIEW_FINANCIAL_DATA',     FALSE),
  ('tech','COLLECT_PAYMENT',         FALSE),
  ('tech','VIEW_ALL_KPI',            FALSE),
  ('tech','MANAGE_USERS',            FALSE),
  ('tech','EDIT_SYSTEM_SETTINGS',    FALSE),
  ('tech','EDIT_TASK_DEFINITIONS',   FALSE),

  -- ── logistics: xem đơn hàng khu vực, tasks kho/giao hàng ────────────────
  ('logistics','VIEW_ALL_CUSTOMERS', FALSE),
  ('logistics','VIEW_OWN_CUSTOMERS', TRUE),
  ('logistics','CREATE_CUSTOMER',    FALSE),
  ('logistics','MANAGE_CUSTOMER',    FALSE),
  ('logistics','CREATE_QUOTE',       FALSE),
  ('logistics','APPROVE_QUOTE',      FALSE),
  ('logistics','CREATE_CONTRACT',    FALSE),
  ('logistics','APPROVE_CONTRACT',   FALSE),
  ('logistics','APPROVE_DISCOUNT',   FALSE),
  ('logistics','START_TASK',         TRUE),
  ('logistics','COMPLETE_OWN_TASK',  TRUE),
  ('logistics','APPROVE_OTHERS_TASK',FALSE),
  ('logistics','MANAGE_BLOCKED_TASK',FALSE),
  ('logistics','VIEW_FINANCIAL_DATA',FALSE),
  ('logistics','COLLECT_PAYMENT',    FALSE),
  ('logistics','VIEW_ALL_KPI',       FALSE),
  ('logistics','MANAGE_USERS',       FALSE),
  ('logistics','EDIT_SYSTEM_SETTINGS',FALSE),
  ('logistics','EDIT_TASK_DEFINITIONS',FALSE),

  -- ── partner: chỉ xem/tạo KH do mình GT ──────────────────────────────────
  ('partner','VIEW_ALL_CUSTOMERS',   FALSE),
  ('partner','VIEW_OWN_CUSTOMERS',   TRUE),
  ('partner','CREATE_CUSTOMER',      TRUE),
  ('partner','MANAGE_CUSTOMER',      FALSE),
  ('partner','CREATE_QUOTE',         FALSE),
  ('partner','APPROVE_QUOTE',        FALSE),
  ('partner','CREATE_CONTRACT',      FALSE),
  ('partner','APPROVE_CONTRACT',     FALSE),
  ('partner','APPROVE_DISCOUNT',     FALSE),
  ('partner','START_TASK',           FALSE),
  ('partner','COMPLETE_OWN_TASK',    FALSE),
  ('partner','APPROVE_OTHERS_TASK',  FALSE),
  ('partner','MANAGE_BLOCKED_TASK',  FALSE),
  ('partner','VIEW_FINANCIAL_DATA',  FALSE),
  ('partner','COLLECT_PAYMENT',      FALSE),
  ('partner','VIEW_ALL_KPI',         FALSE),
  ('partner','MANAGE_USERS',         FALSE),
  ('partner','EDIT_SYSTEM_SETTINGS', FALSE),
  ('partner','EDIT_TASK_DEFINITIONS',FALSE)
) AS p(role_code, pkey, enabled)
JOIN roles r ON r.code = p.role_code
ON CONFLICT (role_id, permission_key)
DO UPDATE SET is_enabled = EXCLUDED.is_enabled, updated_at = NOW();

-- Xác nhận
SELECT r.code, COUNT(*) FILTER (WHERE rp.is_enabled) AS enabled, COUNT(*) AS total
FROM roles r
JOIN role_permissions rp ON rp.role_id = r.id
GROUP BY r.code ORDER BY r.code;
